apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ask8-app
  namespace: argocd
spec:
  destination:
    namespace: ask8-apps
    server: https://kubernetes.default.svc
  project: ask8-project
  source:
    path: wikichart/
    repoURL: https://github.com/askasp/ask8s_charts.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

