
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata-app
  namespace: argocd
spec:
  destination:
    namespace: ask8-apps
    server: https://kubernetes.default.svc
  project: ask8-project
  source:
    helm:
      parameters:
    chart: netdata
    repoURL: netdata https://netdata.github.io/helmchart/
    targetRevision: 3.7.5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
