apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ask8-app
  namespace: argocd
spec:
  destination:
    namespace: ask8-apps
    server: https://kubernetes.default.svc
  project: ask8-project
  source:
    path: wikichart/
    repoURL: https://github.com/askasp/ask8_charts.git
    targetRevision: HEAD
    helm:
          # Extra parameters to set (same as setting through values.yaml, but these take precedence)
          parameters:
          # - name: "nginx-ingress.controller.service.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
          #   value: mydomain.example.com
          # - name: "ingress.annotations.kubernetes\\.io/tls-acme"
          #   value: "true"
          #   forceString: true # ensures that value is treated as a string

          # # Release name override (defaults to application name)
          # releaseName: guestbook

          # Helm values files for overriding values in the helm chart
          # The path is relative to the spec.source.path directory defined above
          valueFiles:
          - values-prod.yaml

          # Values file as block file
          # values: |
          #   ingress:
          #     enabled: true
          #     path: /
          #     hosts:
          #       - mydomain.example.com
          #     annotations:
          #       kubernetes.io/ingress.class: nginx
          #       kubernetes.io/tls-acme: "true"
          #     labels: {}
          #     tls:
          #       - secretName: mydomain-tls
          #         hosts:
          #           - mydomain.example.com



  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

