ingress:
  enabled: true
  className: ""
  annotations:
#      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod-2
      kubernetes.io/tls-acme: "true"

  hosts:
   - host: wiki.akselerasjon.no
     paths:
       - path: /
         pathType: ImplementationSpecific
  tls:
     - secretName: letsencrypt-tls
       hosts:
         - wiki.akselerasjon.no

